plugins { id 'com.android.library' }
android {
    namespace 'org.eversolo.winamp.playlist'
    compileSdk 34
    defaultConfig { minSdk 26 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    api project(':library')
    api project(':playback')
    implementation project(':core')
}
