package org.eversolo.winamp.skin;

import java.util.HashMap;
import java.util.Map;

/**
 * Sprite table for Winamp's GENERIC window - the frame its library-style windows wear,
 * out of gen.bmp and genex.bmp.
 *
 * GENERATED by tools/gen-window-sprites.py. webamp has no media library and so no table to
 * copy, but gen.bmp marks its own pieces: every boundary is drawn in RGB(0,198,255), a
 * colour that appears nowhere else in the bitmap, so the generator measures the pieces
 * rather than guessing them. That matters most for the title alphabet, where every letter
 * is a different width - I is 4 px, M and W are 8.
 *
 * The frame is assembled the same way the playlist window is: fixed corners with a tile
 * repeated between them, so it can be any size.
 */
public final class GenSprites {

    /** Title bar, borders and bottom bar heights, in skin pixels. */
    public static final int TITLE_H = 20;
    public static final int LEFT_W = 11;
    public static final int RIGHT_W = 8;
    public static final int BOTTOM_H = 14;
    public static final int PIECE_W = 25;

    /** The title alphabet is 7 px tall; a space advances this far. */
    public static final int LETTER_H = 7;
    public static final int SPACE_W = 5;
    /** Row of the bright alphabet in gen.bmp, and of the dim one below it. */
    public static final int LETTER_Y = 88;
    public static final int LETTER_Y_INACTIVE = 96;

    /** The close button sits this far into the top-right corner piece. */
    public static final int CLOSE_DX = 14;
    public static final int CLOSE_DY = 3;
    public static final int CLOSE_W = 9;

    /** A push button from genex.bmp. */
    public static final int BUTTON_W = 47;
    public static final int BUTTON_H = 15;

    public static final Map<String, SkinSprites.Rect> SRC = new HashMap<>();
    /** letter -> {x in gen.bmp, width} */
    public static final Map<Character, int[]> LETTERS = new HashMap<>();

    private static void s(String name, String file, int x, int y, int w, int h) {
        SRC.put(name, SkinSprites.rect(file, x, y, w, h));
    }

    private static void letter(char c, int x, int w) {
        LETTERS.put(c, new int[]{x, w});
    }

    public static SkinSprites.Rect src(String name) { return SRC.get(name); }

    /** How wide {@code text} will be in the title alphabet. */
    public static int textWidth(String text) {
        int w = 0;
        for (int i = 0; i < text.length(); i++) {
            int[] l = LETTERS.get(Character.toUpperCase(text.charAt(i)));
            w += l == null ? SPACE_W : l[1];
            w += 1;                       // Winamp leaves a pixel between letters
        }
        return Math.max(0, w - 1);
    }

    static {
        s("GEN_TOP_LEFT", "gen.bmp", 0, 0, 25, 20);
        s("GEN_TOP_FILL", "gen.bmp", 26, 0, 25, 20);
        s("GEN_TITLE_LEFT", "gen.bmp", 52, 0, 25, 20);
        s("GEN_TITLE_FILL", "gen.bmp", 78, 0, 25, 20);
        s("GEN_TITLE_RIGHT", "gen.bmp", 104, 0, 25, 20);
        s("GEN_TOP_RIGHT", "gen.bmp", 130, 0, 25, 20);
        s("GEN_TOP_LEFT_INACTIVE", "gen.bmp", 0, 21, 25, 20);
        s("GEN_TOP_FILL_INACTIVE", "gen.bmp", 26, 21, 25, 20);
        s("GEN_TITLE_LEFT_INACTIVE", "gen.bmp", 52, 21, 25, 20);
        s("GEN_TITLE_FILL_INACTIVE", "gen.bmp", 78, 21, 25, 20);
        s("GEN_TITLE_RIGHT_INACTIVE", "gen.bmp", 104, 21, 25, 20);
        s("GEN_TOP_RIGHT_INACTIVE", "gen.bmp", 130, 21, 25, 20);
        s("GEN_CLOSE_PRESSED", "gen.bmp", 148, 42, 9, 9);
        s("GEN_LEFT_BORDER", "gen.bmp", 127, 42, 11, 29);
        s("GEN_RIGHT_BORDER", "gen.bmp", 139, 42, 8, 29);
        s("GEN_BOTTOM_LEFT", "gen.bmp", 0, 57, 25, 14);
        s("GEN_BOTTOM_FILL", "gen.bmp", 50, 57, 25, 14);
        s("GEN_BOTTOM_RIGHT", "gen.bmp", 100, 57, 25, 14);

        s("GENEX_BUTTON", "genex.bmp", 0, 0, 47, 15);
        s("GENEX_BUTTON_PRESSED", "genex.bmp", 0, 15, 47, 15);
        s("GENEX_SCROLL_UP", "genex.bmp", 0, 30, 15, 15);
        s("GENEX_SCROLL_DOWN", "genex.bmp", 15, 30, 15, 15);
        s("GENEX_SCROLL_UP_PRESSED", "genex.bmp", 28, 30, 15, 15);
        s("GENEX_SCROLL_DOWN_PRESSED", "genex.bmp", 43, 30, 15, 15);
        s("GENEX_SCROLL_HANDLE", "genex.bmp", 57, 30, 13, 30);
        s("GENEX_SCROLL_HANDLE_PRESSED", "genex.bmp", 70, 30, 13, 30);

        letter('A', 1, 6);
        letter('B', 8, 7);
        letter('C', 16, 7);
        letter('D', 24, 6);
        letter('E', 31, 6);
        letter('F', 38, 6);
        letter('G', 45, 7);
        letter('H', 53, 6);
        letter('I', 60, 4);
        letter('J', 65, 6);
        letter('K', 72, 7);
        letter('L', 80, 5);
        letter('M', 86, 8);
        letter('N', 95, 6);
        letter('O', 102, 6);
        letter('P', 109, 6);
        letter('Q', 116, 7);
        letter('R', 124, 7);
        letter('S', 132, 6);
        letter('T', 139, 5);
        letter('U', 145, 6);
        letter('V', 152, 6);
        letter('W', 159, 8);
        letter('X', 168, 7);
        letter('Y', 176, 6);
        letter('Z', 183, 5);
    }

    private GenSprites() {}
}
