package org.eversolo.winamp.skin;

import java.util.HashMap;
import java.util.Map;

/**
 * Sprite atlas for the classic Winamp 2.x windows: the main window and the playlist editor.
 *
 * GENERATED by tools/gen-sprites.py from webamp's skinSprites.ts (MIT), rather than typed
 * by hand or taken from eva's skinformat.json - eva's file contradicts itself in places
 * (it puts the previous-track button at both x=16 and x=93, balance at 174 instead of 177,
 * and mono/stereo at y=43 instead of 41). webamp is a faithful reimplementation and its
 * numbers agree with the real bitmaps.
 *
 * To regenerate:  ./tools/gen-sprites.py PLEDIT   (and --font for the character table)
 *
 * SRC  = where a piece lives inside its .bmp
 * DEST = where it is drawn inside the window; the main window is 275x116, the playlist
 *        editor is sized by PlaylistGeometry.
 */
public final class SkinSprites {

    public static final int WINDOW_W = 275;
    public static final int WINDOW_H = 116;

    /** Bitmap font cell size in text.bmp. */
    public static final int CHAR_W = 5;
    public static final int CHAR_H = 6;

    public static final class Rect {
        public final String file;
        public final int x, y, w, h;
        Rect(String file, int x, int y, int w, int h) {
            this.file = file; this.x = x; this.y = y; this.w = w; this.h = h;
        }
    }

    public static final Map<String, Rect> SRC = new HashMap<>();
    /** char -> {row, col} in text.bmp */
    public static final Map<Character, int[]> FONT = new HashMap<>();

    private static void s(String name, String file, int x, int y, int w, int h) {
        SRC.put(name, new Rect(file, x, y, w, h));
    }

    private static void f(char c, int row, int col) {
        FONT.put(c, new int[]{row, col});
    }

    public static Rect src(String name) { return SRC.get(name); }

    /** For the sibling table in GenSprites, which shares this Rect type. */
    static Rect rect(String file, int x, int y, int w, int h) {
        return new Rect(file, x, y, w, h);
    }

    static {
        s("MAIN_PREVIOUS_BUTTON", "cbuttons.bmp", 0, 0, 23, 18);
        s("MAIN_PREVIOUS_BUTTON_ACTIVE", "cbuttons.bmp", 0, 18, 23, 18);
        s("MAIN_PLAY_BUTTON", "cbuttons.bmp", 23, 0, 23, 18);
        s("MAIN_PLAY_BUTTON_ACTIVE", "cbuttons.bmp", 23, 18, 23, 18);
        s("MAIN_PAUSE_BUTTON", "cbuttons.bmp", 46, 0, 23, 18);
        s("MAIN_PAUSE_BUTTON_ACTIVE", "cbuttons.bmp", 46, 18, 23, 18);
        s("MAIN_STOP_BUTTON", "cbuttons.bmp", 69, 0, 23, 18);
        s("MAIN_STOP_BUTTON_ACTIVE", "cbuttons.bmp", 69, 18, 23, 18);
        s("MAIN_NEXT_BUTTON", "cbuttons.bmp", 92, 0, 23, 18);
        s("MAIN_NEXT_BUTTON_ACTIVE", "cbuttons.bmp", 92, 18, 22, 18);
        s("MAIN_EJECT_BUTTON", "cbuttons.bmp", 114, 0, 22, 16);
        s("MAIN_EJECT_BUTTON_ACTIVE", "cbuttons.bmp", 114, 16, 22, 16);
        s("MAIN_SHUFFLE_BUTTON", "shufrep.bmp", 28, 0, 47, 15);
        s("MAIN_SHUFFLE_BUTTON_DEPRESSED", "shufrep.bmp", 28, 15, 47, 15);
        s("MAIN_SHUFFLE_BUTTON_SELECTED", "shufrep.bmp", 28, 30, 47, 15);
        s("MAIN_SHUFFLE_BUTTON_SELECTED_DEPRESSED", "shufrep.bmp", 28, 45, 47, 15);
        s("MAIN_REPEAT_BUTTON", "shufrep.bmp", 0, 0, 28, 15);
        s("MAIN_REPEAT_BUTTON_DEPRESSED", "shufrep.bmp", 0, 15, 28, 15);
        s("MAIN_REPEAT_BUTTON_SELECTED", "shufrep.bmp", 0, 30, 28, 15);
        s("MAIN_REPEAT_BUTTON_SELECTED_DEPRESSED", "shufrep.bmp", 0, 45, 28, 15);
        s("MAIN_EQ_BUTTON", "shufrep.bmp", 0, 61, 23, 12);
        s("MAIN_EQ_BUTTON_SELECTED", "shufrep.bmp", 0, 73, 23, 12);
        s("MAIN_EQ_BUTTON_DEPRESSED", "shufrep.bmp", 46, 61, 23, 12);
        s("MAIN_EQ_BUTTON_DEPRESSED_SELECTED", "shufrep.bmp", 46, 73, 23, 12);
        s("MAIN_PLAYLIST_BUTTON", "shufrep.bmp", 23, 61, 23, 12);
        s("MAIN_PLAYLIST_BUTTON_SELECTED", "shufrep.bmp", 23, 73, 23, 12);
        s("MAIN_PLAYLIST_BUTTON_DEPRESSED", "shufrep.bmp", 69, 61, 23, 12);
        s("MAIN_PLAYLIST_BUTTON_DEPRESSED_SELECTED", "shufrep.bmp", 69, 73, 23, 12);
        s("MAIN_POSITION_SLIDER_BACKGROUND", "posbar.bmp", 0, 0, 248, 10);
        s("MAIN_POSITION_SLIDER_THUMB", "posbar.bmp", 248, 0, 29, 10);
        s("MAIN_POSITION_SLIDER_THUMB_SELECTED", "posbar.bmp", 278, 0, 29, 10);
        s("MAIN_VOLUME_BACKGROUND", "volume.bmp", 0, 0, 68, 420);
        s("MAIN_VOLUME_THUMB", "volume.bmp", 15, 422, 14, 11);
        s("MAIN_VOLUME_THUMB_SELECTED", "volume.bmp", 0, 422, 14, 11);
        s("MAIN_BALANCE_BACKGROUND", "balance.bmp", 9, 0, 38, 420);
        s("MAIN_BALANCE_THUMB", "balance.bmp", 15, 422, 14, 11);
        s("MAIN_BALANCE_THUMB_ACTIVE", "balance.bmp", 0, 422, 14, 11);
        s("MAIN_STEREO", "monoster.bmp", 0, 12, 29, 12);
        s("MAIN_STEREO_SELECTED", "monoster.bmp", 0, 0, 29, 12);
        s("MAIN_MONO", "monoster.bmp", 29, 12, 27, 12);
        s("MAIN_MONO_SELECTED", "monoster.bmp", 29, 0, 27, 12);
        s("NO_MINUS_SIGN", "numbers.bmp", 9, 6, 5, 1);
        s("MINUS_SIGN", "numbers.bmp", 20, 6, 5, 1);
        s("DIGIT_0", "numbers.bmp", 0, 0, 9, 13);
        s("DIGIT_1", "numbers.bmp", 9, 0, 9, 13);
        s("DIGIT_2", "numbers.bmp", 18, 0, 9, 13);
        s("DIGIT_3", "numbers.bmp", 27, 0, 9, 13);
        s("DIGIT_4", "numbers.bmp", 36, 0, 9, 13);
        s("DIGIT_5", "numbers.bmp", 45, 0, 9, 13);
        s("DIGIT_6", "numbers.bmp", 54, 0, 9, 13);
        s("DIGIT_7", "numbers.bmp", 63, 0, 9, 13);
        s("DIGIT_8", "numbers.bmp", 72, 0, 9, 13);
        s("DIGIT_9", "numbers.bmp", 81, 0, 9, 13);
        s("MAIN_PLAYING_INDICATOR", "playpaus.bmp", 0, 0, 9, 9);
        s("MAIN_PAUSED_INDICATOR", "playpaus.bmp", 9, 0, 9, 9);
        s("MAIN_STOPPED_INDICATOR", "playpaus.bmp", 18, 0, 9, 9);
        s("MAIN_NOT_WORKING_INDICATOR", "playpaus.bmp", 36, 0, 9, 9);
        s("MAIN_WORKING_INDICATOR", "playpaus.bmp", 39, 0, 9, 9);
        s("MAIN_TITLE_BAR", "titlebar.bmp", 27, 15, 275, 14);
        s("MAIN_TITLE_BAR_SELECTED", "titlebar.bmp", 27, 0, 275, 14);
        s("MAIN_EASTER_EGG_TITLE_BAR", "titlebar.bmp", 27, 72, 275, 14);
        s("MAIN_EASTER_EGG_TITLE_BAR_SELECTED", "titlebar.bmp", 27, 57, 275, 14);
        s("MAIN_OPTIONS_BUTTON", "titlebar.bmp", 0, 0, 9, 9);
        s("MAIN_OPTIONS_BUTTON_DEPRESSED", "titlebar.bmp", 0, 9, 9, 9);
        s("MAIN_MINIMIZE_BUTTON", "titlebar.bmp", 9, 0, 9, 9);
        s("MAIN_MINIMIZE_BUTTON_DEPRESSED", "titlebar.bmp", 9, 9, 9, 9);
        s("MAIN_SHADE_BUTTON", "titlebar.bmp", 0, 18, 9, 9);
        s("MAIN_SHADE_BUTTON_DEPRESSED", "titlebar.bmp", 9, 18, 9, 9);
        s("MAIN_CLOSE_BUTTON", "titlebar.bmp", 18, 0, 9, 9);
        s("MAIN_CLOSE_BUTTON_DEPRESSED", "titlebar.bmp", 18, 9, 9, 9);
        s("MAIN_CLUTTER_BAR_BACKGROUND", "titlebar.bmp", 304, 0, 8, 43);
        s("MAIN_CLUTTER_BAR_BACKGROUND_DISABLED", "titlebar.bmp", 312, 0, 8, 43);
        s("MAIN_CLUTTER_BAR_BUTTON_O_SELECTED", "titlebar.bmp", 304, 47, 8, 8);
        s("MAIN_CLUTTER_BAR_BUTTON_A_SELECTED", "titlebar.bmp", 312, 55, 8, 7);
        s("MAIN_CLUTTER_BAR_BUTTON_I_SELECTED", "titlebar.bmp", 320, 62, 8, 7);
        s("MAIN_CLUTTER_BAR_BUTTON_D_SELECTED", "titlebar.bmp", 328, 69, 8, 8);
        s("MAIN_CLUTTER_BAR_BUTTON_V_SELECTED", "titlebar.bmp", 336, 77, 8, 7);
        s("MAIN_SHADE_BACKGROUND", "titlebar.bmp", 27, 42, 275, 14);
        s("MAIN_SHADE_BACKGROUND_SELECTED", "titlebar.bmp", 27, 29, 275, 14);
        s("MAIN_SHADE_BUTTON_SELECTED", "titlebar.bmp", 0, 27, 9, 9);
        s("MAIN_SHADE_BUTTON_SELECTED_DEPRESSED", "titlebar.bmp", 9, 27, 9, 9);
        s("MAIN_SHADE_POSITION_BACKGROUND", "titlebar.bmp", 0, 36, 17, 7);
        s("MAIN_SHADE_POSITION_THUMB", "titlebar.bmp", 20, 36, 3, 7);
        s("MAIN_SHADE_POSITION_THUMB_LEFT", "titlebar.bmp", 17, 36, 3, 7);
        s("MAIN_SHADE_POSITION_THUMB_RIGHT", "titlebar.bmp", 23, 36, 3, 7);
        s("MAIN_WINDOW_BACKGROUND", "main.bmp", 0, 0, 275, 116);

        f('a', 0, 0);
        f('b', 0, 1);
        f('c', 0, 2);
        f('d', 0, 3);
        f('e', 0, 4);
        f('f', 0, 5);
        f('g', 0, 6);
        f('h', 0, 7);
        f('i', 0, 8);
        f('j', 0, 9);
        f('k', 0, 10);
        f('l', 0, 11);
        f('m', 0, 12);
        f('n', 0, 13);
        f('o', 0, 14);
        f('p', 0, 15);
        f('q', 0, 16);
        f('r', 0, 17);
        f('s', 0, 18);
        f('t', 0, 19);
        f('u', 0, 20);
        f('v', 0, 21);
        f('w', 0, 22);
        f('x', 0, 23);
        f('y', 0, 24);
        f('z', 0, 25);
        f('"', 0, 26);
        f('@', 0, 27);
        f(' ', 0, 30);  // space
        f('0', 1, 0);
        f('1', 1, 1);
        f('2', 1, 2);
        f('3', 1, 3);
        f('4', 1, 4);
        f('5', 1, 5);
        f('6', 1, 6);
        f('7', 1, 7);
        f('8', 1, 8);
        f('9', 1, 9);
        f('\u2026', 1, 10);
        f('.', 1, 11);
        f(':', 1, 12);
        f('(', 1, 13);
        f(')', 1, 14);
        f('-', 1, 15);
        f('\'', 1, 16);
        f('!', 1, 17);
        f('_', 1, 18);
        f('+', 1, 19);
        f('\\', 1, 20);
        f('/', 1, 21);
        f('[', 1, 22);
        f(']', 1, 23);
        f('^', 1, 24);
        f('&', 1, 25);
        f('%', 1, 26);
        f(',', 1, 27);
        f('=', 1, 28);
        f('$', 1, 29);
        f('#', 1, 30);
        f('\u00c5', 2, 0);
        f('\u00d6', 2, 1);
        f('\u00c4', 2, 2);
        f('?', 2, 3);
        f('*', 2, 4);
        f('<', 1, 22);
        f('>', 1, 23);
        f('{', 1, 22);
        f('}', 1, 23);

        // ---- playlist editor (pledit.bmp) ----
        // The window is assembled from these: two corners plus a repeating tile per
        // edge, so it can be any size that is 275+25n wide and 58+29n tall.
        s("PLAYLIST_TOP_TILE", "pledit.bmp", 127, 21, 25, 20);
        s("PLAYLIST_TOP_LEFT_CORNER", "pledit.bmp", 0, 21, 25, 20);
        s("PLAYLIST_TITLE_BAR", "pledit.bmp", 26, 21, 100, 20);
        s("PLAYLIST_TOP_RIGHT_CORNER", "pledit.bmp", 153, 21, 25, 20);
        s("PLAYLIST_TOP_TILE_SELECTED", "pledit.bmp", 127, 0, 25, 20);
        s("PLAYLIST_TOP_LEFT_SELECTED", "pledit.bmp", 0, 0, 25, 20);
        s("PLAYLIST_TITLE_BAR_SELECTED", "pledit.bmp", 26, 0, 100, 20);
        s("PLAYLIST_TOP_RIGHT_CORNER_SELECTED", "pledit.bmp", 153, 0, 25, 20);
        s("PLAYLIST_LEFT_TILE", "pledit.bmp", 0, 42, 12, 29);
        s("PLAYLIST_RIGHT_TILE", "pledit.bmp", 31, 42, 20, 29);
        s("PLAYLIST_BOTTOM_TILE", "pledit.bmp", 179, 0, 25, 38);
        s("PLAYLIST_BOTTOM_LEFT_CORNER", "pledit.bmp", 0, 72, 125, 38);
        s("PLAYLIST_BOTTOM_RIGHT_CORNER", "pledit.bmp", 126, 72, 150, 38);
        s("PLAYLIST_VISUALIZER_BACKGROUND", "pledit.bmp", 205, 0, 75, 38);
        s("PLAYLIST_SHADE_BACKGROUND", "pledit.bmp", 72, 57, 25, 14);
        s("PLAYLIST_SHADE_BACKGROUND_LEFT", "pledit.bmp", 72, 42, 25, 14);
        s("PLAYLIST_SHADE_BACKGROUND_RIGHT", "pledit.bmp", 99, 57, 50, 14);
        s("PLAYLIST_SHADE_BACKGROUND_RIGHT_SELECTED", "pledit.bmp", 99, 42, 50, 14);
        s("PLAYLIST_SCROLL_HANDLE_SELECTED", "pledit.bmp", 61, 53, 8, 18);
        s("PLAYLIST_SCROLL_HANDLE", "pledit.bmp", 52, 53, 8, 18);
        s("PLAYLIST_ADD_URL", "pledit.bmp", 0, 111, 22, 18);
        s("PLAYLIST_ADD_URL_SELECTED", "pledit.bmp", 23, 111, 22, 18);
        s("PLAYLIST_ADD_DIR", "pledit.bmp", 0, 130, 22, 18);
        s("PLAYLIST_ADD_DIR_SELECTED", "pledit.bmp", 23, 130, 22, 18);
        s("PLAYLIST_ADD_FILE", "pledit.bmp", 0, 149, 22, 18);
        s("PLAYLIST_ADD_FILE_SELECTED", "pledit.bmp", 23, 149, 22, 18);
        s("PLAYLIST_REMOVE_ALL", "pledit.bmp", 54, 111, 22, 18);
        s("PLAYLIST_REMOVE_ALL_SELECTED", "pledit.bmp", 77, 111, 22, 18);
        s("PLAYLIST_CROP", "pledit.bmp", 54, 130, 22, 18);
        s("PLAYLIST_CROP_SELECTED", "pledit.bmp", 77, 130, 22, 18);
        s("PLAYLIST_REMOVE_SELECTED", "pledit.bmp", 54, 149, 22, 18);
        s("PLAYLIST_REMOVE_SELECTED_SELECTED", "pledit.bmp", 77, 149, 22, 18);
        s("PLAYLIST_REMOVE_MISC", "pledit.bmp", 54, 168, 22, 18);
        s("PLAYLIST_REMOVE_MISC_SELECTED", "pledit.bmp", 77, 168, 22, 18);
        s("PLAYLIST_INVERT_SELECTION", "pledit.bmp", 104, 111, 22, 18);
        s("PLAYLIST_INVERT_SELECTION_SELECTED", "pledit.bmp", 127, 111, 22, 18);
        s("PLAYLIST_SELECT_ZERO", "pledit.bmp", 104, 130, 22, 18);
        s("PLAYLIST_SELECT_ZERO_SELECTED", "pledit.bmp", 127, 130, 22, 18);
        s("PLAYLIST_SELECT_ALL", "pledit.bmp", 104, 149, 22, 18);
        s("PLAYLIST_SELECT_ALL_SELECTED", "pledit.bmp", 127, 149, 22, 18);
        s("PLAYLIST_SORT_LIST", "pledit.bmp", 154, 111, 22, 18);
        s("PLAYLIST_SORT_LIST_SELECTED", "pledit.bmp", 177, 111, 22, 18);
        s("PLAYLIST_FILE_INFO", "pledit.bmp", 154, 130, 22, 18);
        s("PLAYLIST_FILE_INFO_SELECTED", "pledit.bmp", 177, 130, 22, 18);
        s("PLAYLIST_MISC_OPTIONS", "pledit.bmp", 154, 149, 22, 18);
        s("PLAYLIST_MISC_OPTIONS_SELECTED", "pledit.bmp", 177, 149, 22, 18);
        s("PLAYLIST_NEW_LIST", "pledit.bmp", 204, 111, 22, 18);
        s("PLAYLIST_NEW_LIST_SELECTED", "pledit.bmp", 227, 111, 22, 18);
        s("PLAYLIST_SAVE_LIST", "pledit.bmp", 204, 130, 22, 18);
        s("PLAYLIST_SAVE_LIST_SELECTED", "pledit.bmp", 227, 130, 22, 18);
        s("PLAYLIST_LOAD_LIST", "pledit.bmp", 204, 149, 22, 18);
        s("PLAYLIST_LOAD_LIST_SELECTED", "pledit.bmp", 227, 149, 22, 18);
        s("PLAYLIST_ADD_MENU_BAR", "pledit.bmp", 48, 111, 3, 54);
        s("PLAYLIST_REMOVE_MENU_BAR", "pledit.bmp", 100, 111, 3, 72);
        s("PLAYLIST_SELECT_MENU_BAR", "pledit.bmp", 150, 111, 3, 54);
        s("PLAYLIST_MISC_MENU_BAR", "pledit.bmp", 200, 111, 3, 54);
        s("PLAYLIST_LIST_BAR", "pledit.bmp", 250, 111, 3, 54);
        s("PLAYLIST_CLOSE_SELECTED", "pledit.bmp", 52, 42, 9, 9);
        s("PLAYLIST_COLLAPSE_SELECTED", "pledit.bmp", 62, 42, 9, 9);
        s("PLAYLIST_EXPAND_SELECTED", "pledit.bmp", 150, 42, 9, 9);
    }

    private SkinSprites() {}
}
